@MinimalAPIs_HostAddress = https://localhost:7097

GET {{MinimalAPIs_HostAddress}}/todos

###

POST {{MinimalAPIs_HostAddress}}/todos
Content-Type: application/json

{
  "name":"water plants",
  "isComplete":false
}

###

GET {{MinimalAPIs_HostAddress}}/todos/complete

###
