@HostAddress = https://localhost:7097

### Create a Todo

POST {{HostAddress}}/todos
Content-Type: application/json
{
  "name": "water plants",
  "isComplete": false
}

### Create a completed Todo

POST {{HostAddress}}/todos
Content-Type: application/json
{
  "name": "wash the motorbike",
  "isComplete": true
}

### Create batch Todo

POST {{HostAddress}}/todos/batch
Content-Type: application/json
[
  {
    "name": "water plants",
    "isComplete": false
  },
  {
    "name": "unplug devices",
    "isComplete": false
  }
]

### Get all Todos

GET {{HostAddress}}/todos

### Get a specific Todo

@getId=1
GET {{HostAddress}}/todos/{{getId}}

### Get all completed Todos

GET {{HostAddress}}/todos/complete

### Delete a Todo

@deleteId=1
DELETE {{HostAddress}}/todos/{{deleteId}}

### Update a Todo

@putId=2
PUT {{HostAddress}}/todos/{{putId}}
Content-Type: application/json

{
  "isComplete": true
}
